package net.ccbluex.liquidbounce.utils

object StaffList {
    const val CUBECRAFT: String = "S4nne " +
            "Fesa " +
            "99th_DutchScary " +
            "Soulless_Unity " +
            "EggyWarz " +
            "Efcluke94 " +
            "SanCookie " +
            "CKelting262 " +
            "rubik_cube_man " +
            "ToonBer " +
            "Kloska " +
            "xThunder_ " +
            "CapitanGato " +
            "SuperSuccubus " +
            "Otherworlden " +
            "ssunsett " +
            "Hqteful " +
            "Alexp192 " +
            "4Moonlightt " +
            "ALM " +
            "xSchulzis " +
            "Muhx " +
            "Goofy_Unity " +
            "ThijsBlocker " +
            "Redned " +
            "Lyriie " +
            "JustNathie " +
            "JokeKaedee " +
            "Elivat " +
            "MDeann " +
            "Basketman13 " +
            "AnolTongi " +
            "Alemiz " +
            "Camezonda "

    const val KKCRAFT: String = "Creeper_Hello Kun_God hanhan_api Regotly_Long"
    const val HYPIXEL: String = "Hypixel " +
            "Rezzus " +
            "AgentK " +
            "Cryptkeeper " +
            "Minikloon " +
            "Plancke " +
            "Slothpixel " +
            "NoxyD " +
            "Jayavarmen " +
            "aPunch " +
            "Gerbor12 " +
            "JordWG " +
            "LeBrillant " +
            "Pensul " +
            "LadyBleu " +
            "Citria " +
            "DeluxeRose " +
            "TheBirmanator " +
            "TorWolf " +
            "Rhune " +
            "Greeenn " +
            "Fr0z3n " +
            "SnowyPai " +
            "Rozsa " +
            "Quack " +
            "ZeaBot " +
            "Cheesey " +
            "MCVisuals " +
            "carstairs95 " +
            "DistrictGecko " +
            "inventivetalent " +
            "JacobRuby " +
            "Judg3 " +
            "LandonHP " +
            "Liffeh " +
            "xHascox " +
            "DEADORKAI " +
            "Brandonjja " +
            "skyerzz " +
            "Dctr " +
            "AdamWho " +
            "jamzs " +
            "Phaige " +
            "Likaos " +
            "Plummel " +
            "Bloozing " +
            "BlocksKey " +
            "MistressEldrid " +
            "Nausicaah " +
            "ChiLynn " +
            "TheMGRF " +
            "Revengeee " +
            "_PolynaLove_ " +
            "Sylent_ " +
            "Teddy " +
            "Relenter " +
            "_fudgiethewhale " +
            "sfarnham " +
            "WilliamTiger " +
            "vinny8ball666 " +
            "Nitroholic_ " +
            "Donpireso " +
            "ConnorLinfoot " +
            "RapidTheNerd " +
            "eeyitscoco " +
            "Cecer " +
            "Externalizable " +
            "Bembo " +
            "Taytale " +
            "JamieTheGeek " +
            "williamgburns " +
            "BOGA32 " +
            "boomerzap " +
            "MFN " +
            "Gainful " +
            "Octaverei " +
            "TacNayn " +
            "TimeDeo " +
            "idhoom " +
            "7so " +
            "1sweet " +
            "jinaaan " +
            "ev2n " +
            "eissaa " +
            "mohmad_q8 " +
            "1daykel " +
            "ximtaig_ " +
            "nshme " +
            "comsterr " +
            "e9_ " +
            "1meko " +
            "1lab " +
            "mk_f16 " +
            "loovq " +
            "_sadeq " +
            "nv0ola " +
            "1f5amh___3oo " +
            "frecss217 " +
            "xmz7 " +
            "a2bod " +
            "eyeso_diamond " +
            "bunkrat " +
            "1rana " +
            "1ahmd " +
            "1heyimhasson_ " +
            "casteret " +
            "1elyy " +
            "1zeyad " +
            "lt1x " +
            "firas " +
            "postme " +
            "3mmr " +
            "xl2d " +
            "yzed " +
            "y2men " +
            "iv2a " +
            "_nonameishere_ " +
            "0hfault " +
            "deficency " +
            "anauri " +
            "xluffy1 " +
            "kinderbueno__ " +
            "_revoox_ " +
            "xidayzer " +
            "i7ilin " +
            "1adam__ " +
            "27bk " +
            "ventz_ " +
            "awfultimes " +
            "ahm2d " +
            "gsomar " +
            "mvp11 " +
            "xxkhaledxxcraft " +
            "aymann_ " +
            "1iraqi " +
            "rambokinq " +
            "undertest " +
            "zswift " +
            "strongest0ne " +
            "neverletyouknow " +
            "zixgamer " +
            "sanfoor_j " +
            "ixghoul_ " +
            "imbexsl_ " +
            "glowdown_ " +
            "hunter47 " +
            "fexoranep " +
            "1reyleigh " +
            "420waffle " +
            "ywgiz " +
            "sweetyalice " +
            "xfahadq " +
            "mr3nb_ " +
            "akash1004 " +
            "zaytonaaa " +
            "rma7o " +
            "mr_1990 " +
            "iali_305 " +
            "wacros " +
            "lwwh " +
            "pynifical " +
            "rivsci " +
            "itsjuan_ " +
            "meedo_qb " +
            "_r3 " +
            "1speedo_ " +
            "_justidk " +
            "505t " +
            "xzvv " +
            "mauveracer " +
            "_1hypersx_ " +
            "rayqquaza " +
            "swivee " +
            "absqtulate " +
            "opgaming2009 " +
            "vhagardracarys " +
            "luffy404 " +
            "faisaal420 " +
            "hdzt " +
            "sunsnipebeastwtf " +
            "_odex " +
            "1ashu " +
            "n13m_ " +
            "callinu " +
            "sh59 " +
            "drnyx " +
            "iisrab5bgii " +
            "haoeris " +
            "lxrayanxl " +
            "toxiclayer " +
            "greatm7md " +
            "brksfrb2 " +
            "madix707 " +
            "hnxrr " +
            "1sweetty " +
            "ohhhhqls " +
            "solidfying " +
            "_i_b " +
            "escoco " +
            "dreadpirater0b " +
            "aboshxm " +
            "0ryze " +
            "spuvr " +
            "va_1 " +
            "kingpvp90 " +
            "rieus " +
            "prebowed " +
            "mitsichu " +
            "gogglas " +
            "battlebay " +
            "32lbo " +
            "7far_8bor " +
            "evenfai " +
            "hlazny " +
            "valrm "

    const val PIKA: String = "Max " +
            "voodootje0 " +
            "MrFrenco " +
            "JustThiemo " +
            "Wrath " +
            "Andeh " +
            "Nirahz " +
            "stupxd " +
            "Botervrij " +
            "Subvalent " +
            "Apo2xd " +
            "Arrly " +
            "Minecraft_leg " +
            "CaptainGeoGR " +
            "Thijme01 " +
            "ChickenDinnr " +
            "Crni_ " +
            "MrGownz " +
            "Outscale " +
            "MrEpiko " +
            "Crveni_Marlboro " +
            "zMqrcc " +
            "_Stella_xD " +
            "Stormidity " +
            "TryToHitMe " +
            "Alparo_ " +
            "CandyOP " +
            "Astrospeh " +
            "TinCanL " +
            "TheTrueNova " +
            "FIKOZ " +
            "DarkVenom7 " +
            "caila5 " +
            "Lpkfvip " +
            "i9BAR " +
            "voodootjeo " +
            "TryHardMarktin " +
            "Axteroid " +
            "Yanique1 " +
            "JstMental " +
            "QuFox " +
            "TTHM " +
            "shozu " +
            "Aeqlian " +
            "NxqL " +
            "iFkiller " +
            "xDeleted " +
            "_Nikki99 " +
            "SgtBordem " +
            "Sanified " +
            "M7Games_HD " +
            "DanielT_ " + 
            "Zxga " +
            "Ungluecklicher " +
            "zireb " +
            "GAMBL3T " +
            "RunYourShordie " +
            "ScorchedX " +
            "zSeann " +
            "YouTubeMemes " +
            "CreeperDxD " +
            "Saifanx1942 " +
            "arham19 " +
            "prober90 "

    const val BMC: String = "iDhoom " +
            "7sO " +
            "Jinaaan " +
            "comsterr " +
            "1Sweet " +
            "Ev2n " +
            "xMz7 " +
            "1Daykel " +
            "mohmad_q8 " +
            "xImTaiG_ " +
            "Nshme " +
            "1Rana " +
            "Refolt " +
            "e9_ " +
            "1LaB " +
            "1HeyImHasson_ " +
            "Bunkrat " +
            "yzed " +
            "NonameIsHere " +
            "sadeq " +
            "loovq " +
            "nv0ola " +
            "1Ahmd " +
            "xiDayzer " +
            "Firas " +
            "deficency " +
            "EyesO_Diamond " +
            "Taysiir " +
            "0Nada " +
            "Meedo_qb " +
            "1flyn " +
            "F2rris " +
            "LwwH " +
            "RamboKinq " +
            "iTsJuan " +
            "Casteret " +
            "superentinel " +
            "Fcris " +
            "XDiaa " +
            "plumsdust " +
            "Aymann_ " +
            "Iv2a " +
            "Zaainab " +
            "KinderBueno__ " +
            "E3Y " +
            "1Ely " +
            "420zero " +
            "xL2d " +
            "DoNotApproach " +
            "tonton01 " +
            "Postme " +
            "berriesdust " +
            "FaisalVibes " +
            "Sanfoor_J " +
            "Hunter47 " +
            "A2boD " +
            "0hFault " +
            "oTalal " +
            "ImMEHDI " +
            "QKUM " +
            "the_over_dust " +
            "Jxicide " +
            "D34th4U " +
            "Mwl4 " +
            "xLuffy1 " +
            "iMrxDJ " +
            "Tvrki " +
            "5ald_KSA " +
            "A2bd " +
            "Rma7o " +
            "1AhMaD " +
            "JustRois " +
            "ReNovel " +
            "AbdelAzez " +
            "CallinU " +
            "MADIX707 " +
            "VirtuallyBlack " +
            "R3 " +
            "0RyZe " +
            "CerealWithNxMilk " +
            "StrongesT0ne " +
            "plaintiveness " +
            "itsqkay " +
            "1Meran " +
            "qLaith " +
            "tHeViZi " +
            "alk52 " +
            "Nar69 " +
            "1MiDo " +
            "zixgamer " +
            "akash1004 " +
            "MVP11 " +
            "Invincib1le " +
            "TargetConfirmed " +
            "0Taha " +
            "meowmawmeow " +
            "EngineerBnedr " +
            "FexoraNEP " +
            "Z_1HypersX_Z " +
            "Revoox " +
            "Watchdog " +
            "Os2ama_ " +
            "1OdeY " +
            "Zz__Mr3nb__zZ " +
            "NullFinder_ " +
            "5_O5 " +
            "1Reyleigh " +
            "Ownersies " +
            "Pynifical " +
            "xzvv " +
            "AbuKhaleel " +
            "72DR " +
            "Bradenton " +
            "Aboshxm " +
            "recklessperson " +
            "Lauderhill " +
            "Wacros " +
            "1Mohamad " +
            "v7Oner__ " +
            "FaaaRis " +
            "zZiiu " +
            "420WaFFLe " +
            "JustIdk " +
            "puwsa " +
            "UnderTest " +
            "sev2ene " +
            "AnkaraView " +
            "yaaser " +
            "SweetyAlice " +
            "faisal911_b " +
            "Just_XYZ " +
            "KLERINPARIS " +
            "mhmoom " +
            "2del " +
            "Jarxay " +
            "TheWarriorTricky " +
            "rivsci " +
            "Gs0247 " +
            "ALEXBIGPROGAMER " +
            "kajo_ " +
            "StrengthGing " +
            "LAZANYA1 " +
            "sh59 " +
            "Smolczes " +
            "dangerousarea21 " +
            "b6l " +
            "X_POLE " +
            "_odex " +
            "Y3K6 " +
            "1Hazify " +
            "Lolobica " +
            "_Ka5 " +
            "M7md " +
            "preboww " +
            "rfe8 " +
            "ItsSafe " +
            "Multiplikaton " +
            "1Hephaistos " +
            "iZ3EM " +
            "CardBoardClip " +
            "deep_winner " +
            "1Smvl0 " +
            "jZIU " +
            "Tyshh " +
            "dxs7 " +
            "DUTCU " +
            "akthem " +
            "Evoless " +
            "Neeres"

    const val ARERAPVP: String = "Agera001 " +
            "Krashe85 " +
            "milanskyy " +
            "Neruxov " +
            "softrelax " +
            "quiu " +
            "exac123 " +
            "Ant4b " +
            "tenfey " +
            "bumyyy1 " +
            "s11an " +
            "spookyjonn " +
            "smothes " +
            "MilkyDream " +
            "22aroma " +
            "Ska1ras " +
            "Twitch_Weathers " +
            "cyceki " +
            "oldlegend " +
            "HEMECUYA " +
            "Uister " +
            "kairomuza " +
            "Rustas23 " +
            "Akiroxy " +
            "montegs " +
            "Duffy_Who " +
            "tiroeson " +
            "ne_dasty"

    const val HYPEMC: String = "chromocat " +
            "KaVlVi " +
            "Twintle " +
            "teisenshi " +
            "_MerticksX_ " +
            "CcPhoenixcC " +
            "rope " +
            "milian " +
            "miamha " +
            "docya " +
            "tudaiobrattno " +
            "x4bb " +
            "loqxnew " +
            "RydiEndi " +
            "Lia2806 " +
            "Gamrely " +
            "Heron " +
            "Ryafkaa " +
            "SoMDeaS " +
            "_GromoV_ " +
            "ygolokk " +
            "Pomachka58 " +
            "LISSKX " +
            "v1nd1go " +
            "Ksenchiks " +
            "FixVaR " +
            "Max540 " +
            "Biikysi " +
            "De_La_Vult " +
            "Akiro49 " +
            "Antos4597 " +
            "Looon " +
            "Bratskyy " +
            "Sursus_S " +
            "ItzAKreyz " +
            "fondik33 " +
            "_tepan098kop_ " +
            "xXx_ST0RM_xXx " +
            "Munchen " +
            "_Or1on_ " +
            "DimonGonBon " +
            "_Dead_Lord_ " +
            "Maksun65yg47tq " +
            "Chizzylegend " +
            "MEDYK " +
            "312 " +
            "Grr441235 " +
            "pinm_qw " +
            "rubick_dash " +
            "IsterBEAk " +
            "Pro100pavel2006 " +
            "Yaguzhinskiy " +
            "Hi11Ti " +
            "glebgeniy " +
            "swiGEMAAOO " +
            "Mr_GeoMheo " +
            "филин223 " +
            "king335xxx " +
            "sardelika5567 " +
            "fwamvm " +
            "Ryder46 " +
            "YaKudZa_MaRo " +
            "TimoG03 "

    const val SUERPCRAFT: String = "TheFlamingOMG " +
            "ImD4mn_x " +
            "Biancirs " +
            "34_ " +
            "Juanilo10 " +
            "prijak125 " +
            "duartetops " +
            "YenSword "
    const val VIMEMC: String = "Tori_que "+
            "KeZixx "
    const val GOMMA: String = "4ch3los " +
            "bemoty " +
            "Clexxer " +
            "GommeHD " +
            "IchMagKeksexD " +
            "Klaus " +
            "lukas81298 " +
            "Marius051099 " +
            "Acex " +
            "FancyPlay " +
            "fantaflash " +
            "Jpx3 " +
            "Kaooot " +
            "LinuxServer " +
            "lvkaas " +
            "Summerfeeling " +
            "sxrhat " +
            "TrainmasterHD " +
            "uScoutz " +
            "einJqn " +
            "ImTxm " +
            "Leoooon " +
            "Zockernetzwerk " +
            "0Taube " +
            "4zig " +
            "Abgxlehnt " +
            "Ason68 " +
            "BeatZap " +
            "BitConi " +
            "DanNick " +
            "debandiete " +
            "DerAutist " +
            "domme0hd " +
            "Dreeaming " +
            "DrNutella " +
            "freudelos " +
            "FourGoldChains " +
            "Fxntom " +
            "iowaniklas " +
            "ItzMarvin23 " +
            "jsnmoin " +
            "KissenschlachtLP " +
            "Laubfrosch7 " +
            "laufe " +
            "Laurens2408 " +
            "lukidercooli " +
            "m0riLp " +
            "Maariuus " +
            "Mxik " +
            "madman1000 " +
            "maisuee " +
            "pewtu " +
            "Polarsterne " +
            "sinischneeflocke " +
            "Slarox " +
            "Tim_Stefan_Maria " +
            "TREM_27 " +
            "Triomino " +
            "UselessGeld " +
            "Vacted " +
            "valentinsan " +
            "Vokabelheft " +
            "Vortrag " +
            "yanno3000 " +
            "zTohru " +
            "zVetrox " +
            "Zunano " +
            "CheeseZocker " +
            "FriendlyDarleen " +
            "nevermiind " +
            "ogii " +
            "Pascas " +
            "Teerve " +
            "114 " +
            "Angestellt " +
            "blutrot " +
            "CalamityFreddi " +
            "CuzImTom " +
            "Cxyy " +
            "DerEisbaer " +
            "DerSchlenderman " +
            "DoctorWann " +
            "Dqniiel " +
            "einChad " +
            "Fernverkehr " +
            "Fey " +
            "FuchsiDE " +
            "gaBer_HD " +
            "geladen " +
            "ItsLazorTV " +
            "kapitulieren " +
            "KleckFleck " +
            "Kruemmel " +
            "la_coneja " +
            "Laugenbrezel " +
            "LeFlurex " +
            "leKireax " +
            "Lenneeey " +
            "Leondopulus " +
            "liebesschwur " +
            "Liisa " +
            "LikeByCookie " +
            "Maloneneis " +
            "MarcelBTW " +
            "Mittelamerika " +
            "Mxln " +
            "Robekh " +
            "Schnitzelmaxl " +
            "Seelenmeer " +
            "Semolius " +
            "SilbernesGold " +
            "SkyDiscovery " +
            "Stepheee " +
            "summervibing " +
            "svaay " +
            "ThatsLuca " +
            "Tschlaubii " +
            "Verlassener " +
            "Voltarix " +
            "W1fu " +
            "xKashiro " +
            "zAimed " +
            "ZettelRaus " +
            "Zwunja " +
            "_starhuntress_ "

    const val GAMSTER: String = "Henriks9 " +
            "Liviu1010 " +
            "ItsB2_ " +
            "Skarnyk " +
            "crosby108 " +
            "M3ti_ " +
            "Mezedak1 " +
            "OsmiumRedox " +
            "pepinillo_crudo " +
            "Space_turtle9 " +
            "Tini_Alina " +
            "_ShadowXD " +
            "mihaaiiii " +
            "Zipette " +
            "Megasus " +
            "Daniell214 " +
            "pintux " +
            "Biee_MB " +
            "ItsKRONX11 " +
            "EroinaMea " +
            "Alex_Rosu " +
            "Raul7896 " +
            "Melanholyyy " +
            "HerDreams " +
            "JustMoon2330 " +
            "qmarcu " +
            "Suffocative " +
            "vxcus " +
            "AutoClickerM5 " +
            "officialMex " +
            "lennoxlotl " +
            "iTz_Lucky " +
            "MutFame " +
            "vento " +
            "Mariaxxaa " +
            "miramausii " +
            "Dark4ever " +
            "Nacktbild " +
            "Bazaraki " +
            "DarkAndBlue " +
            "totKing " +
            "byHugZ " +
            "kyssyou "
}